server:
  port: 9072
#  servlet:
#    contextPath: /user-service

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: user-service

ribbon:
  restclient:
    enabled: true
